- district: "นาบอน"
  group: 1
  subDistricts:
    - "นาบอน"
    - "ทุ่งสง"
    - "แก้วแสน"
- district: "ร่อนพิบูลย์ (1)"
  group: 1
  subDistricts:
    - "เสาธง"
    - "ควนพัง"
    - "ควนเกย" 
    - "ควนชุม"
- district: "ร่อนพิบูลย์ (2)"
  group: 1
  subDistricts:    
    - "ร่อนพิบูลย์"
    - "หินตก"
- district: "ทุ่งใหญ่ (1)"
  group: 1
  subDistricts:   
    - "ท่ายาง"
    - "ทุ่งใหญ่"
    - "กุแหระ" 
    - "ทุ่งสัง"
- district: "ทุ่งใหญ่ (2)"
  group: 1
  subDistricts:   
    - "ปริก"
    - "กรุงหยัน"
    - "บางรูป"
- district: "ฉวาง (1)"
  group: 1
  subDistricts:   
  - "ฉวาง"
  - "นาแว"
  - "ห้วยปริก"
  - "กะเปียด" 
  - "จันดี"
- district: "ฉวาง (2)"
  group: 1
  subDistricts:   
  - "ไม้เรียง"
  - "ไสหร้า"
  - "นากะชะ" 
  - "ละอาย"
  - "นาเขลียง"
- district: "พิปูน"
  group: 1
  subDistricts:   
  - "พิปูน"
  - "กะทูน"
  - "เขาพระ"
  - "ยางค้อม"
  - "ควนกลาง"
- district: "ช้างกลาง"
  group: 1
  subDistricts:   
  - "ช้างกลาง"
  - "หลักช้าง"
  - "สวนขัน"
- district: "เชียรใหญ่"
  group: 1
  subDistricts:
  - "เชียรใหญ่"
  - "ท่าขนาน" 
  - "บ้านกลาง" 
  - "บ้านเนิน" 
  - "ไสหมาก" 
  - "ท้องลำเจียก" 
  - "เสือหึง" 
  - "การะเกด" 
  - "เขาพระบาท" 
  - "แม่เจ้าอยู่หัว" 
- district: "ถ้ำพรรณรา"
  group: 2
  subDistricts:
  - "ถ้ำพรรณรา"
  - "คลองเส"
  - "ดุสิต"
- district: "ทุ่งสง (1)"
  group: 2
  subDistricts:
  - "ปากแพรก"
  - "ที่วัง"
- district: "ทุ่งสง (2)"
  group: 2
  subDistricts:
  - "ชะมาย"
  - "หนองหงส์"
  - "ควนกรด"
- district: "ทุ่งสง (3)"
  group: 2
  subDistricts:
  - "นาไม้ไผ่"
  - "นาหลวงเสน"
  - "เขาโร"
  - "กะปาง"
- district: "ทุ่งสง (4)"
  group: 2
  subDistricts:
  - "น้ำตก"
  - "ถ้ำใหญ่"
  - "นาโพธิ์"
  - "เขาขาว"
- district: "จุฬาภรณ์"
  group: 2
  subDistricts:
  - "บ้านควนมุด"
  - "บ้านชะอวด"
  - "ควนหนองคว้า"
  - "ทุ่งโพธิ์"
  - "นาหมอบุญ"
  - "สามตำบล"
- district: "ชะอวด (1)"
  group: 2
  subDistricts:
  - "ชะอวด"
  - "วังอ่าง"
  - "เคร็ง"
  - "ท่าเสม็ด"
  - "บ้านตูล"
- district: "ชะอวด (2)"
  group: 2
  subDistricts:
  - "ท่าประจะ"
  - "เกาะขันธ์"
  - "ขอนหาด"
  - "ควนหนองหงษ์"
  - "เขาพระทอง"
  - "นางหลง"
- district: "บางขัน (1)"
  group: 2
  subDistricts:
  - "บางขัน"
  - "วังหิน"
- district: "บางขัน (2)"
  group: 2
  subDistricts:
  - "บ้านนิคม"
  - "บ้านลำนาว"
- district: "ขนอม"
  group: 3
  subDistricts:
  - "ขนอม"
  - "ควนทอง"
  - "ท้องเนียน"
- district: "หัวไทร (1)"
  group: 3
  subDistricts:
  - "หัวไทร"
  - "หน้าสตน"
  - "เกาะเพชร"
  - "บ้านราม"
  - "ท่าซอม"
  - "บางนบ"
- district: "หัวไทร (2)"
  group: 3
  subDistricts:
  - "เขาพังไกร"
  - "แหลม"
  - "ทรายขาว"
  - "ควนชะลิก"
  - "รามแก้ว"
- district: "พรหมคีรี"
  group: 3
  subDistricts:
  - "พรหมโลก"
  - "บ้านเกาะ"
  - "อินคีรี"
  - "ทอนหงส์"
  - "นาเรียง"
- district: "พระพรหม"
  group: 3
  subDistricts:
  - "นาพรุ"
  - "นาสาร"
  - "ท้ายสำเภา"
  - "ช้างซ้าย"
- district: "เมือง (1)"
  group: 3
  subDistricts:
  - "ปากพูน"
  - "ท่างิ้ว"
  - "นาทราย"
- district: "เมือง (2)"
  group: 3
  subDistricts:
  - "ในเมือง"
  - "บางจาก"
  - "มะม่วงสองต้น"
- district: "เมือง (3)"
  group: 3
  subDistricts:
  - "ท่าเรือ"
  - "กำแพงเซา"
  - "นาเคียน"
- district: "เมือง (4)"
  group: 3
  subDistricts:
  - "คลัง"
  - "โพธิ์เสด็จ"
  - "ปากนคร"
- district: "เมือง (5)"
  group: 3
  subDistricts:
  - "ท่าไร่"
  - "ท่าซัก"
  - "ท่าวัง"
  - "ไชยมนตรี"
- district: "นบพิตำ"
  group: 4
  subDistricts:
  - "นบพิตำ"
  - "กรุงชิง"
  - "กะหรอ"
  - "นาเหรง"
- district: "สิชล (1)"
  group: 4
  subDistricts:
  - "เสาเภา"
  - "ทุ่งปรัง"
  - "เทพราช"
  - "ฉลอง"
  - "เปลี่ยน"
- district: "สิชล (2)"
  group: 4
  subDistricts:
  - "สิชล"
  - "ทุ่งใส"
  - "เขาน้อย"
  - "สี่ขีด"
- district: "ลานสกา"
  group: 4
  subDistricts:
  - "เขาแก้ว"
  - "ลานสกา"
  - "ท่าดี"
  - "กำโลน"
  - "ขุนทะเล"
- district: "เฉลิมพระเกียรติ"
  group: 4
  subDistricts:
  - "เชียรเขา"
  - "ดอนตรอ"
  - "สวนหลวง"
  - "ทางพูน"
- district: "ปากพนัง (1)"
  group: 4
  subDistricts:
  - "ปากพนัง"
  - "เกาะทวด"
  - "ท่าพยา"
  - "ปากแพรก"
  - "บางตะพง"
  - "แหลมตะลุมพุก"
  - "ปากพนังฝั่งตะวันออก"
  - "ปากพนังฝั่งตะวันตก"
- district: "ปากพนัง (2)"
  group: 4
  subDistricts:
  - "คลองน้อย"
  - "ขนาบนาก"
  - "คลองกระบือ"
  - "หูล่อง"
  - "ชะเมา"
  - "ป่าระกำ"
  - "บางพระ"
  - "บ้านเพิง"
  - "บ้านใหม่"
  - "บางศาลา"
- district: "ท่าศาลา (1)"
  group: 4
  subDistricts:
  - "ท่าศาลา"
  - "ไทยบุรี"
  - "ดอนตะโก"
- district: "ท่าศาลา (2)"
  group: 4
  subDistricts:
  - "ท่าขึ้น"
  - "สระแก้ว"
  - "โพธิ์ทอง"
- district: "ท่าศาลา (3)"
  group: 4
  subDistricts:
  - "กลาย"
  - "ตลิ่งชัน"
  - "หัวตะพาน"
  - "โมคลาน"